abbr -a -g music "/Users/vegardlandsverk/Music"
abbr -a -g img "/Users/vegardlandsverk/Pictures"
abbr -a -g desktop "/Users/vegardlandsverk/Desktop"
abbr -a -g btc "/Users/vegardlandsverk/Alfred.alfredpreferences/workflows/user.workflow.8BEDA4A2-A978-46D5-A9A3-05A8EDCD61C7"
abbr -a -g la "/Users/vegardlandsverk/Library/LaunchAgents"
abbr -a -g xampp "/Users/vegardlandsverk/.bitnami/stackman/machines/xampp/volumes/root/htdocs"
abbr -a -g movies "/Users/vegardlandsverk/Movies"
abbr -a -g film "/Users/vegardlandsverk/Movies"
abbr -a -g doc "/Users/vegardlandsverk/Documents"
abbr -a -g documents "/Users/vegardlandsverk/Documents"
abbr -a -g docs "/Users/vegardlandsverk/Documents"
abbr -a -g stud "/Users/vegardlandsverk/Documents/Studier"
abbr -a -g studier "/Users/vegardlandsverk/Documents/Studier"
abbr -a -g prog "/Users/vegardlandsverk/Documents/Progging"
abbr -a -g progging "/Users/vegardlandsverk/Documents/Progging"
abbr -a -g kod "/Users/vegardlandsverk/Documents/Progging"
abbr -a -g koding "/Users/vegardlandsverk/Documents/Progging"
abbr -a -g gcal "/Users/vegardlandsverk/Documents/Progging/skienok/google_calendar"
abbr -a -g gcallogs "/Users/vegardlandsverk/Documents/Progging/google_calendar/logs"
abbr -a -g db "/Users/vegardlandsverk/Documents/Progging/NTNU/TDT4145"
abbr -a -g pu "/Users/vegardlandsverk/Documents/Progging/NTNU/TDT4140"
abbr -a -g pproject "/Users/vegardlandsverk/Documents/Progging/NTNU/TDT4113"
abbr -a -g plab "/Users/vegardlandsverk/Documents/Progging/NTNU/TDT4113"
abbr -a -g ku_prog "/Users/vegardlandsverk/Documents/Progging/samf"
abbr -a -g schmelk "/Users/vegardlandsverk/Documents/Progging/samf/schmelk.no"
abbr -a -g hippo "/Users/vegardlandsverk/Documents/Progging/samf/google-sheets-scripts"
abbr -a -g vim_dir "/Users/vegardlandsverk/.vim"
abbr -a -g orientering "/Users/vegardlandsverk/Documents/Orientering"
abbr -a -g v22 "/Users/vegardlandsverk/OneDrive\ -\ NTNU/GoodNotes/V22"
abbr -a -g bio "/Users/vegardlandsverk/OneDrive\ -\ NTNU/GoodNotes/V22/Bio\ -\ PSYK4123"
abbr -a -g kognitiv "/Users/vegardlandsverk/OneDrive\ -\ NTNU/GoodNotes/V22/Kognitiv\ -\ PSYK4122"
abbr -a -g pr2 "/Users/vegardlandsverk/OneDrive\ -\ NTNU/GoodNotes/V22/PR2\ -\ PSYK4302"
abbr -a -g onedrive "/Users/vegardlandsverk/OneDrive"
abbr -a -g onedrive-ntnu "/Users/vegardlandsverk/OneDrive\ -\ NTNU"
abbr -a -g gdrive "/Users/vegardlandsverk/Mi\ unidad"
abbr -a -g samf "/Users/vegardlandsverk/Documents/Progging/samf"
abbr -a -g trump "/Users/vegardlandsverk/Documents/Progging/trump-generator"
abbr -a -g hybel "/Users/vegardlandsverk/Documents/Progging/personal/hybel.no"
abbr -a -g hoc "/Users/vegardlandsverk/Documents"
abbr -a -g hocs "/Users/vegardlandsverk/Documents"
abbr -a -g tools "/Users/vegardlandsverk/Documents/Progging/python-tools"
abbr -a -g confd "/Users/vegardlandsverk/.config/fish/conf.d"
abbr -a -g hjemmeside "/Users/vegardlandsverk/Documents/Progging/personal/hjemmeside"
abbr -a -g finn "/Users/vegardlandsverk/Documents/Progging/personal/finn.no-scraper"
abbr -a -g tise "/Users/vegardlandsverk/Documents/Progging/personal/tise.com-scraper"
abbr -a -g personal "/Users/vegardlandsverk/Documents/Progging/personal"
abbr -a -g ticketswap "/Users/vegardlandsverk/Documents/Progging/personal/ticketswap.com-scraper"
abbr -a -g mbp "/Users/vegardlandsverk/Documents/Progging/personal/mbp-anti-crash"
abbr -a -g daemon "/Library/LaunchDaemons"
abbr -a -g daemons "/Library/LaunchDaemons"
abbr -a -g eject "/Users/vegardlandsverk/Library/Application\ Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.560CE6E9-EF00-4A24-BF6F-390D3411BCBC"
abbr -a -g scrape "/Users/vegardlandsverk/Documents/Progging/personal/scrapere"
abbr -a -g scraper "/Users/vegardlandsverk/Documents/Progging/personal/scrapere"
abbr -a -g scrapere "/Users/vegardlandsverk/Documents/Progging/personal/scrapere"
abbr -a -g finn_bolig "/Users/vegardlandsverk/Documents/Progging/personal/scrapere/finn_no_bolig"
abbr -a -g h23 "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2023/H23"
abbr -a -g nevro "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2023/H23/Kognitiv\ nevro"
abbr -a -g genetics "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2023/H23/Behaviour\ Genetics"
abbr -a -g mat-inf "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2023/H23/MAT-INF1100"
abbr -a -g matinf "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2023/H23/MAT-INF1100"
abbr -a -g hoihoi "/Users/vegardlandsverk/.config/fish"
abbr -a -g dow "/Users/vegardlandsverk/Downloads"
abbr -a -g plink-dir "/Users/vegardlandsverk/Downloads/plink_mac_20231018"
abbr -a -g hapmap "/Users/vegardlandsverk/Downloads/hapmap1"
abbr -a -g sice-dir "/Users/vegardlandsverk/Downloads/PRSice_mac"
abbr -a -g chapter-10 "/Users/vegardlandsverk/Downloads/data_chapter10"
abbr -a -g ku-intern "/Users/vegardlandsverk/Documents/Progging/samf/ku-internsider"
abbr -a -g franks "/Users/vegardlandsverk/Documents/Progging/samf/franks_dameridning"
abbr -a -g fire "/Users/vegardlandsverk/.config/fish"
abbr -a -g v24 "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2024/V24"
abbr -a -g in3050 "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2024/V24/Kunstig\ Intelligens\ (IN3050)"
abbr -a -g usit "/Users/vegardlandsverk/Documents/Progging/uio/USIT"
abbr -a -g mm-bot "/Users/vegardlandsverk/Documents/Progging/uio/USIT/it-hjelp-mm-bot"
abbr -a -g optishift "/Users/vegardlandsverk/Documents/Progging/OptiShift"
abbr -a -g opti "/Users/vegardlandsverk/Documents/Progging/uio/USIT/optiShift"
abbr -a -g 4415 "/Users/vegardlandsverk/OneDrive\ -\ Universitetet\ i\ Oslo/GoodNotes/2025/V25/PSYC4415"
abbr -a -g ticketmaster "/Users/vegardlandsverk/Documents/Progging/personal/scrapere/ticketmaster"
